version: "3.5"
services:
  question-generator-mongo:
    image: mongo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
    networks:
      - question-generation-network
  question-generator-server:
    build: ./QuizRTapi
    labels:
      SERVICE_7001_NAME: QuestionGenerator
    depends_on:
      - question-generator-mongo
      - rabbitmq
    networks:
      - question-generation-network
    ports:
      - "7001:7001"
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    networks:
      - question-generation-network
    ports:
      - "15672:15672"
      - "5672:5672"
networks:
  question-generation-network:
    name: quizrt-network
    external: true