version: "3"
services:
  question-generator-mongo:
    image: mongo
    volumes:
      - ${WEBAPP_STORAGE_HOME}/site:/data/db
    ports:
      - "27017:27017"
  question-generator-server:
    build: ./QuizRTapi
    labels:
      SERVICE_7001_NAME: QuestionGenerator
    depends_on:
      - question-generator-mongo
      - rabbitmq
    ports:
      - "7001"
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"